app = "aqua-voyage"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[build]
  [build.args]
    SECRET_KEY_BASE = "YOUR_SECRET_KEY_BASE"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  release_command = "bin/rails db:migrate RAILS_ENV=production"
