
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: db
  port: 5432
  

development:
  <<: *default
  database: aqua_voyage_development

test:
  <<: *default
  database: aqua_voyage_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>